include $(CLEAR_VARS)
LOCAL_MODULE := GCMod
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := GCMod/GCam_6.1.021_Advanced_V1.5.190418.1850.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_DEX_PREOPT := false
LOCAL_OVERRIDES_PACKAGES := Camera2, Snap
include $(BUILD_PREBUILT)
